version: "3.5"
services:
  cert-sync:
    image: registry.gitlab.developers.cam.ac.uk/uis/infra/gvm-deployment/gvmd
    volumes:
      - gvm-var-lib:/var/lib/gvm
    command: greenbone-certdata-sync --curl --verbose
    depends_on:
      - "gvmd"
    networks:
      - gvm-network
