version: '3.2'
services:
  cert-sync:
    image: registry.gitlab.developers.cam.ac.uk/wh330/gvm-deployment/gvmd
    volumes:
      - gvm-var-lib:/var/lib/gvm
    command: greenbone-certdata-sync --curl --verbose
    depends_on:
      - "gvmd"
