version: "3.3"
services:
  gvm-postgres:
    image: registry.gitlab.developers.cam.ac.uk/uis/infra/gvm-deployment/gvm-postgres
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=gvmd
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=gvmduser
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gvmd:
    image: registry.gitlab.developers.cam.ac.uk/uis/infra/gvm-deployment/gvmd
    environment:
      - GVMD_POSTGRESQL_URI=postgresql://gvmduser:mypassword@gvm-postgres:5432/gvmd?application_name=gvmd
    volumes:
      - gvm-var-lib:/var/lib/gvm
      - run-redis:/var/run/redis
      - openvas-var-lib:/var/lib/openvas
      - run-ospd:/var/run/ospd
      - ./certs:/usr/var/lib/gvm
    depends_on:
      - "gvm-postgres"

  gsad:
    image: registry.gitlab.developers.cam.ac.uk/uis/infra/gvm-deployment/gsad
    ports:
      - 8080:80
    environment:
      - GVMD_HOST=gvmd
      - GVMD_PORT=9390
    depends_on:
      - "gvmd"

  # Default scanner connected through Unix domain socket.
  openvas:
    # LISTENING /var/run/ospd/ospd.sock
    # CONNECTED /var/run/redis/redis.sock
    image: registry.gitlab.developers.cam.ac.uk/uis/infra/gvm-deployment/openvas
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    volumes:
      - run-redis:/var/run/redis
      - openvas-var-lib:/opt/gvm/var/lib/openvas
      - run-ospd:/var/run/ospd
    depends_on:
      - "gvm-postgres"

  # It is recommended to add vm.overcommit_memory=1 into
  # /etc/systcl.conf on the host
  redis:
    # LISTENING /var/run/redis/redis.sock
    image: redis:6.0.9
    volumes:
      - run-redis:/var/run/redis
      - redis-data:/data
      - ./chart/redis/redis-openvas.conf:/redis-openvas.conf
    command: redis-server /redis-openvas.conf
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    depends_on:
      - "openvas"

volumes:
  redis-data:
  gvm-var-lib:
  postgres-data:
  run-redis:
  openvas-var-lib:
  run-ospd:
