version: '3.2'
services:
  nvt-sync:
    build:
      context: ./openvas
    volumes:
      - openvas-var-lib:/var/lib/openvas
      - run-redis:/var/run/redis
      - run-ospd:/var/run/ospd
    command: su - gvm -c "greenbone-nvt-sync"

    depends_on:
      - "gvmd"
