version: "3.5"
services:
  scap-sync:
    image: registry.gitlab.developers.cam.ac.uk/uis/infra/fps/gvm-deployment/gvmd
    volumes:
      - gvm-var-lib:/var/lib/gvm
    command: greenbone-feed-sync --type SCAP
    depends_on:
      - "gvmd"
    networks:
      - gvm-network
