version: '3.2'
services:
  scap-sync:
    build:
      context: ./gvmd
    volumes:
      - openvas-var-lib:/var/lib/openvas
      - gvm-var-lib:/var/lib/gvm
      - run-redis:/var/run/redis
      - run-ospd:/var/run/ospd
    command: greenbone-scapdata-sync --curl --verbose

    depends_on:
      - "gvmd"
