apiVersion: batch/v1
kind: Job
metadata:
  name: gvm-nvt-sync
  namespace: default
  labels:
    app.kubernetes.io/instance: gvm-gvm
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: gvm-gvm
    spec:
      restartPolicy: Never
      containers:
        - name: gvm
          image: "registry.gitlab.developers.cam.ac.uk/wh330/gvm-deployment/openvas:7"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "su gvm -c 'greenbone-nvt-sync'"]
          volumeMounts:
            - name: data-volume
              subPath: openvas
              mountPath: /opt/gvm/var/lib/openvas
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume