apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gvm-scap-cert-data-sync
  namespace: gvm
  labels:
    app.kubernetes.io/instance: gvm-gvm
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: gvm-gvm
        spec:
          restartPolicy: Never
          containers:
            - name: gvm
              image: "registry.gitlab.developers.cam.ac.uk/uis/infra/gvm-deployment/gvmd:9"
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "greenbone-certdata-sync; sleep 3; greenbone-scapdata-sync; true"]
              volumeMounts:
                - name: data-volume
                  subPath: scap-data
                  mountPath: /var/lib/gvm/scap-data
                - name: data-volume
                  subPath: cert-data
                  mountPath: /var/lib/gvm/cert-data
          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: data-volume
