apiVersion: v1
kind: Service
metadata:
  labels:
    app: gvmd-db
    release: gvm
    role: master
  name: gvm-gvmd-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: gvmd-db
    release: gvm
    role: master
