apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gvm.fullname" . }}-gvmd
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- $_ := set . "applicationNameSuffix" "gvmd" }}
  {{- include "gvm.labels" . | nindent 4 }}
  {{- $_ := set . "applicationNameSuffix" "" }}
spec:
  replicas: {{ .Values.gvmdReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gvm.name" . }}-gvmd
      app.kubernetes.io/instance: {{ include "gvm.instance" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gvm.name" . }}-gvmd
        app.kubernetes.io/instance: {{ include "gvm.instance" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ tpl .Values.image.gvmd.registry . }}/{{ tpl .Values.image.gvmd.repository . }}:{{ tpl .Values.image.gvmd.tag . }}"
          imagePullPolicy: {{ .Values.image.gvmd.pullPolicy }}
          env:
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: password
            - name: GVMD_POSTGRESQL_URI
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRESQL_HOST):5432/gvmd?application_name=gvmd"
          ports:
            - name: gvmd
              containerPort: 9390
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: gvmd
            initialDelaySeconds: 150
            periodSeconds: 80
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: gvmd
            initialDelaySeconds: 120
            periodSeconds: 10
          volumeMounts:
            - name: run-dir
              mountPath: /run
            - name: run-dir
              subPath: gvm
              mountPath: /run/gvm
            - name: run-dir
              subPath: ospd
              mountPath: /run/ospd
            - name: data-volume
              subPath: openvas
              mountPath: /var/lib/openvas
            - name: data-volume
              subPath: gvm
              mountPath: /var/lib/gvm
            - name: data-volume
              subPath: scap-data
              mountPath: /var/lib/gvm/scap-data
            - name: data-volume
              subPath: cert-data
              mountPath: /var/lib/gvm/cert-data
            - name: data-volume
              subPath: certs
              mountPath: /usr/var/lib/gvm
            - name: data-volume
              subPath: gvm/gvmd
              mountPath: /var/lib/gvm/gvmd
            - name: data-volume
              subPath: data-objects
              mountPath: /var/lib/gvm/data-objects
            # - name: gvmd-log-config
            #   mountPath: /etc/gvm
          resources:
            {{- toYaml .Values.resources.gvmd | nindent 12 }}
        - name: {{ .Chart.Name }}-openvas-connector
          image: "{{ tpl .Values.image.socat.registry . }}/{{ tpl .Values.image.socat.repository . }}:{{ tpl .Values.image.socat.tag . }}"
          imagePullPolicy: {{ .Values.image.socat.pullPolicy }}
          args: ["-d", "-d", "UNIX-LISTEN:/run/ospd/ospd.sock,fork", "TCP4-CONNECT:{{ include "gvm.fullname" . }}-openvas:9391"]
          volumeMounts:
            - name: run-dir
              mountPath: /run
            - name: run-dir
              subPath: ospd
              mountPath: /run/ospd
          resources:
            {{- toYaml .Values.resources.gvmdOpenvasConnector | nindent 12 }}
      volumes:
        - name: run-dir
          emptyDir: {}
        - name: data-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . | default (include "gvm.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: gvmd-log-config
          configMap:
            name: {{ include "gvm.fullname" . }}-gvmd-log-config
            items:
            - key: gvmd-log-config
              path: gvmd_log.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
