apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gvm.fullname" . }}-openvas
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- $_ := set . "applicationNameSuffix" "openvas" }}
  {{- include "gvm.labels" . | nindent 4 }}
  {{- $_ := set . "applicationNameSuffix" "" }}
spec:
  replicas: {{ .Values.openvasReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gvm.name" . }}-openvas
      app.kubernetes.io/instance: {{ include "gvm.instance" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gvm.name" . }}-openvas
        app.kubernetes.io/instance: {{ include "gvm.instance" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ tpl .Values.image.openvas.registry . }}/{{ tpl .Values.image.openvas.repository . }}:{{ tpl .Values.image.openvas.tag . }}"
          imagePullPolicy: {{ .Values.image.openvas.pullPolicy }}
          volumeMounts:
            - name: run-dir
              mountPath: /var/run
            - name: redis-socket-dir
              mountPath: /var/run/redis
            - name: data-volume
              subPath: openvas
              mountPath: /opt/gvm/var/lib/openvas
          resources:
            {{- toYaml .Values.resources.openvas | nindent 12 }}
        - name: {{ .Chart.Name }}-openvas-listener
          image: "{{ tpl .Values.image.socat.registry . }}/{{ tpl .Values.image.socat.repository . }}:{{ tpl .Values.image.socat.tag . }}"
          imagePullPolicy: {{ .Values.image.socat.pullPolicy }}
          args: ["-d", "-d", "TCP4-LISTEN:9391,fork", "UNIX-CONNECT:/var/run/ospd/ospd.sock"]
          ports:
            - name: openvas
              containerPort: 9391
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: openvas
            initialDelaySeconds: 120
            periodSeconds: 60
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: openvas
            initialDelaySeconds: 50
            periodSeconds: 10
          volumeMounts:
            - name: run-dir
              mountPath: /var/run
          resources:
            {{- toYaml .Values.resources.openvasListener | nindent 12 }}
        - name: {{ .Chart.Name }}-redis
          image: "{{ tpl .Values.image.redis.registry . }}/{{ tpl .Values.image.redis.repository . }}:{{ tpl .Values.image.redis.tag . }}"
          imagePullPolicy: {{ .Values.image.redis.pullPolicy }}
          command:
            - redis-server
            - "/redis-master/redis.conf"
          volumeMounts:
            - name: redis-socket-dir
              mountPath: /var/run/redis
            - name: data-volume
              mountPath: /data
              subPath: redis/gvm-openvas
            - name: config
              mountPath: /redis-master
          resources:
            {{- toYaml .Values.resources.openvasRedis | nindent 12 }}
      volumes:
        - name: run-dir
          emptyDir: {}
        - name: redis-socket-dir
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "gvm.fullname" . }}-redis-openvas-config
            items:
            - key: redis-config
              path: redis.conf
        - name: data-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . | default (include "gvm.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
