apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "gvm.fullname" . }}-scap-cert-data-sync
  namespace: {{ .Values.namespace.name }}
  labels:
  {{- $_ := set . "applicationNameSuffix" "scap-cert-data-sync" }}
  {{- include "gvm.labels" . | nindent 4 }}
  {{- $_ := set . "applicationNameSuffix" "" }}
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "gvm.name" . }}-scap-cert-data-sync
            app.kubernetes.io/instance: {{ include "gvm.instance" . }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ tpl .Values.image.gvmd.registry . }}/{{ tpl .Values.image.gvmd.repository . }}:{{ tpl .Values.image.gvmd.tag . }}"
              imagePullPolicy: {{ .Values.image.gvmd.pullPolicy }}
              # env:
              #   - name: COMMUNITY_SCAP_RSYNC_FEED
              #     value: rsync://feed.community.greenbone.net:/scap-data
              #   - name: COMMUNITY_CERT_RSYNC_FEED
              #     value: rsync://feed.community.greenbone.net:/cert-data
              command: ["sh", "-c", "greenbone-feed-sync --type CERT; sleep 3; greenbone-feed-sync --type SCAP; true"]
              volumeMounts:
                - name: run-gvm
                  mountPath: /run/gvm
                - name: data-volume
                  subPath: scap-data
                  mountPath: /var/lib/gvm/scap-data
                - name: data-volume
                  subPath: cert-data
                  mountPath: /var/lib/gvm/cert-data
          volumes:
            - name: run-gvm
              emptyDir: {}
            - name: data-volume
              {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ tpl .Values.persistence.existingClaim . | default (include "gvm.fullname" .) }}
              {{- else }}
              emptyDir: {}
              {{- end }}
