---
# Postgres database credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace:  {{ .Values.namespace.name }}
  labels:
  {{- include "gvm.labels" . | nindent 4 }}
data:
  host: {{ default "" .Values.postgres.host | b64enc | quote }}
  username: {{ default "" .Values.postgres.username | b64enc | quote }}
  password: {{ default "" .Values.postgres.password | b64enc | quote }}
