# Postgres secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace:  {{ .Values.namespace.name }}
  labels:
  {{- include "gvm.labels" . | nindent 4 }}
data:
  username: {{ default "" .Values.postgres.username | b64enc | quote }}
  password: {{ default "" .Values.postgres.password | b64enc | quote }}

---
# GVMd secrets for gvm-script commands
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gmpClient.secretName }}
  namespace:  {{ .Values.namespace.name }}
  labels:
  {{- include "gvm.labels" . | nindent 4 }}
data:
  username: {{ default "" .Values.gmpClient.username | b64enc | quote }}
  password: {{ default "" .Values.gmpClient.password | b64enc | quote }}
